#!/usr/bin/env ruby

message_file = ARGV[0]
message = File.read(message_file)

$regex = /^(\[(#\d+|chore|features)\])|(Merge)/

if !$regex.match(message)
  puts <<-EOS
ಠ_ಠ Looks like your commit message does not start with its Pivotal Tracker Story ID
A good commit message looks like this:

  [#9532134] I did something awesome to improve some feature

If you have no Story ID use [chore] instead:

  [chore] Some rogue task I did

Thanks for making our git history awesome!
  EOS
  exit 1
end
